// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGISfJZJOvFDDtmR3g_bZn3RQdvGsSkA',
    appId: '1:816038681095:web:d558417de220260b6aa8a2',
    messagingSenderId: '816038681095',
    projectId: 'test-6e099',
    authDomain: 'test-6e099.firebaseapp.com',
    storageBucket: 'test-6e099.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMFY6tp2bB1UHXFFREeKM20pDImnJHKA',
    appId: '1:816038681095:android:c8c2615d7222ad576aa8a2',
    messagingSenderId: '816038681095',
    projectId: 'test-6e099',
    storageBucket: 'test-6e099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHrAIPNZTaH03px-qswl0ya6_vQk3lo6A',
    appId: '1:816038681095:ios:dca20ad82389b6106aa8a2',
    messagingSenderId: '816038681095',
    projectId: 'test-6e099',
    storageBucket: 'test-6e099.appspot.com',
    iosClientId: '816038681095-h9uv692mer65qapp3tkmq5anmlel5spo.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHrAIPNZTaH03px-qswl0ya6_vQk3lo6A',
    appId: '1:816038681095:ios:dca20ad82389b6106aa8a2',
    messagingSenderId: '816038681095',
    projectId: 'test-6e099',
    storageBucket: 'test-6e099.appspot.com',
    iosClientId: '816038681095-h9uv692mer65qapp3tkmq5anmlel5spo.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
